services:
  postgres:
    container_name: pg_sql
    image: postgres
    environment:
      POSTGRES_USER: ghaith
      POSTGRES_PASSWORD: ghaith
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - microservices-net
    restart: unless-stopped
    ports:
      - 5432:5432

networks:
  microservices-net:
    driver: bridge
volumes:
  postgres: